JiraWorkLogApp.Web/JiraWorkLogApp.Web/ViewModels/DailyWorkLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JiraWorkLogApp.Web.ViewModels
{
    public class DailyWorkLog
    {
        public string Date { get; set; }
        public decimal Time { get; set; }
    }
}

JiraWorkLogApp.Web/JiraWorkLogApp.Web/ViewModels/SummaryWorkLog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JiraWorkLogApp.Web.ViewModels
{
    public class SummaryWorkLog
    {
        public string SprintName { get; set; }
        public string IssueId { get; set; }
        public string Summary { get; set; }
        public string LoggedDate { get; set; }
        public decimal LoggedTime { get; set; }
    }
}

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;
using Microsoft.Owin.Security;

namespace JiraWorkLogApp.Web.Controllers
{
    public class AccountController : Controller
    {
        public void SignIn()
        {
            // Send an OpenID Connect sign-in request.
            if (!Request.IsAuthenticated)
            {
                HttpContext.GetOwinContext().Authentication.Challenge(new AuthenticationProperties { RedirectUri = "/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

        public void SignOut()
        {
            string callbackUrl = Url.Action("SignOutCallback", "Account", routeValues: null, protocol: Request.Url.Scheme);

            HttpContext.GetOwinContext().Authentication.SignOut(
                new AuthenticationProperties { RedirectUri = callbackUrl },
                OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
        }

        public ActionResult SignOutCallback()
        {
            if (Request.IsAuthenticated)
            {
                // Redirect to home page if the user is authenticated.
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JiraWorkLogApp.Web.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult ShowError()
        {
            return View();
        }
    }
}

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JiraWorkLogApp.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles ="Admin")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Controllers/WorkLogController.cs
using JiraWorkLogApp.Data;
using JiraWorkLogApp.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JiraWorkLogApp.Web.Controllers
{
    [Authorize]
    public class WorkLogController : Controller
    {
        private readonly WorkLogRepository _workLogRepository;
        public WorkLogController()
        {
            _workLogRepository = new WorkLogRepository();
        }

        // GET: WorkLog
        public ActionResult Daily()
        {
            var userId = User.Identity.Name;
            var allLogs = _workLogRepository.GetAllWorkLogs();
            var dailyList = from wl in allLogs
                            where wl.UserId == userId
                            group wl by wl.LoggedDate into grp
                            select grp;

            var workLogList = new List<DailyWorkLog>();

            foreach (var item in dailyList)
            {
                var wl = new DailyWorkLog
                {
                    Date = item.Key.Value.ToShortDateString(),
                    Time = item.Sum(x => x.LoggedTime)
                };
                workLogList.Add(wl);
            }

            return View(workLogList);
        }

        public ActionResult Summary()
        {
            var userId = User.Identity.Name;
            var allLogs = _workLogRepository.GetAllWorkLogs();
            var summaryList = from wl in allLogs
                              where wl.UserId == userId
                              select wl;

            var workLogList = new List<SummaryWorkLog>();
            foreach (var item in summaryList.OrderBy(x=>x.LoggedDate))
            {
                var wl = new SummaryWorkLog
                {
                    SprintName = item.SprintName,
                    IssueId = item.IssueId,
                    Summary = item.Summary,
                    LoggedDate = item.LoggedDate.Value.ToShortDateString(),
                    LoggedTime = item.LoggedTime
                };
                workLogList.Add(wl);
            }

            return View(workLogList);
        }

        public ActionResult Team()
        {
            return View();
        }

    }
}

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>AutoConcept Work Logs</h1>
    <p class="lead">This application can be used to track your worklogs from Jira</p>
</div>

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AutoConcept Work Logs</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AutoConcept Work Logs", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Daily", "Daily", "WorkLog")</li>
                    <li>@Html.ActionLink("Summary", "Summary", "WorkLog")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Team", "WorkLog")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AutoConcept Work Logs</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Views/WorkLog/Daily.cshtml
@model IEnumerable<JiraWorkLogApp.Web.ViewModels.DailyWorkLog>

@{
    ViewBag.Title = "Daily";
}

<h2>Daily Logs: Total (@Model.Sum(x => x.Time).ToString("0.00"))</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @item.Time.ToString("0.00")
        </td>
    </tr>
}

</table>

JiraWorkLogApp.Web/JiraWorkLogApp.Web/Views/WorkLog/Summary.cshtml
@model IEnumerable<JiraWorkLogApp.Web.ViewModels.SummaryWorkLog>


@{
    ViewBag.Title = "Daily";
}

<h2>Daily Logs: Total (@Model.Sum(x => x.LoggedTime).ToString("0.00"))</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SprintName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssueId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Summary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoggedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LoggedTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SprintName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssueId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoggedDate)
            </td>
            <td>
                @item.LoggedTime.ToString("0.00")
            </td>
        </tr>
    }

</table>